[client]
representative = "Mike Hood, P.E."
org_name = "City of Little Rock"
address_street = "701 W Markham Street"
address_city = "Little Rock"
address_state = "Arkansas"
address_zip = 72201
contact_name = "David Hopkins, P.E."
contact_phone = "501-371-4475"
contact_email = "dhopkins@littlerock.gov"

[engineer]
firm = "Crafton, Tull & Associates, Inc."
address_street = "10825 Financial Centre Parkway"
address_city = "Little Rock"
address_state = "Arkansas"
address_zip = 72211
senior = "Brad Peterson"
contact = "Sam Kreimeyer"
phone = "501-664-3245 ext.1167"
email = "sam.kreimeyer@craftontull.com"


[project]
name = "Pratt Remmel Road Extension"
description ='''Pratt Remmel Road is to be extended to Frazier Pike, and Frazier Pike is to be widened approximately 1000ft
to the east and west.'''

    [project.location]
    address_street = "Pratt Remmel Road"
    address_city = "Little Rock"
    address_state = "Arkansas"
    address_zip = 72201
    parcel_id = "24L0150001500"
    legal = '''Beginning at some point thence to some others.
    containing 100 square feet, more or less'''
